name: Release Go Binary

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: true

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            runs-on: windows-latest
          - goos: linux
            goarch: amd64
            runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install dependencies (Windows)
      if: matrix.goos == 'windows'
      run: |
        choco install mingw
    
    - name: Install dependencies (Linux)
      if: matrix.goos == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev libgtk-3-dev pkg-config
    
    - name: Build binary (Windows)
      if: matrix.goos == 'windows'
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      run: |
        mkdir -p bin
        go build -o bin/excel-schema-generator.exe .
    
    - name: Build binary (Linux)
      if: matrix.goos == 'linux'
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      run: |
        mkdir -p bin
        go build -o bin/excel-schema-generator .
    
    - name: Rename binary for release
      run: |
        if [ "${{ matrix.goos }}" = "windows" ]; then
          mv bin/excel-schema-generator.exe bin/excel-schema-generator-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        else
          mv bin/excel-schema-generator bin/excel-schema-generator-${{ matrix.goos }}-${{ matrix.goarch }}
        fi
      shell: bash
    
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/excel-schema-generator-*
        tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # Build universal binary for macOS
  build-macos-universal:
    name: Build macOS Universal Binary
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Universal Binary
      run: |
        chmod +x ./scripts/build_macos.sh
        ./scripts/build_macos.sh
    
    - name: Rename binary for release
      run: |
        mv bin/excel-schema-generator bin/excel-schema-generator-darwin-universal
    
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/excel-schema-generator-darwin-universal
        tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}