name: Test Build

on:
  workflow_dispatch:
    inputs:
      build_description:
        description: 'Build description (optional)'
        required: false
        default: 'Manual test build'

permissions:
  contents: read

jobs:
  test-build-matrix:
    name: Test Build
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            runs-on: windows-latest
            binary_name: excel-schema-generator.exe
          - goos: linux
            goarch: amd64
            runs-on: ubuntu-latest
            binary_name: excel-schema-generator
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install dependencies (Windows)
      if: matrix.goos == 'windows'
      run: |
        choco install mingw
    
    - name: Install dependencies (Linux)
      if: matrix.goos == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      run: |
        mkdir -p bin
        go build -o bin/${{ matrix.binary_name }} .
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: excel-schema-generator-${{ matrix.goos }}-${{ matrix.goarch }}
        path: bin/${{ matrix.binary_name }}
        retention-days: 1
        if-no-files-found: error

  test-build-macos-universal:
    name: Test Build macOS Universal
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Universal Binary
      run: |
        chmod +x ./scripts/build_macos.sh
        ./scripts/build_macos.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: excel-schema-generator-darwin-universal
        path: bin/excel-schema-generator
        retention-days: 1
        if-no-files-found: error